// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Prefer env vars injected pelo Vite na build/deploy
const SUPABASE_URL = (import.meta as any).env?.VITE_SUPABASE_URL || "https://xcdlujjyyirlzykfzhkm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = (import.meta as any).env?.VITE_SUPABASE_PUBLISHABLE_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhjZGx1amp5eWlybHp5a2Z6aGttIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyNjU0ODYsImV4cCI6MjA3MTg0MTQ4Nn0.3M5eqBh3FLKtdTNySj4vlIxjlJKCpLrpsf5x365Tl_k";

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error('Missing Supabase environment variables (VITE_SUPABASE_URL / VITE_SUPABASE_PUBLISHABLE_KEY)');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});